# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Clone garden builder
      run: git clone --depth 1 git@github.com:Shelob9/digitial-garden-builder.git
    - name: Copy garden.json
      run: cp garden.json garden.json
    - name: Copy env
      run: cp client.env digitial-garden-builder/client/.env   
    - name: Install garden
      run: cd cd digitial-garden-builder && yarn
    - name: Build garden HTML
      run: yarn grow
    - name: List files in out
      run: cd out && ls
